### ISSUE TITLE
guh-cli crashes by adding a new device

### ISSUE THREAD

**Issue by Boernsman** [guh/guh-cli#10]
Everytime i try to add a new device, guh-cli quits and returns an error.
It seems that problem occurs only on Mac OS Terminals, it doesnt matter if i execute guh-cli local or via ssh. 

MacOSX10.10.3
Terminal 2.5.3
Python2.7.10

  File "/usr/lib/python2.7/dist-packages/guh/selector.py", line 97, in process_selection_menu
    curses.curs_set(1)
_curses.error: curs_set() returned ERR

**Comment by t-mon** [comment]
remove the line `export TERM="xterm-color"` in you ~/.profile did the trick
