### ISSUE TITLE
countdowns: guh-cli doesn't state the countdown name

### ISSUE THREAD

**Issue by simonhoenegger** [guh/guh-cli#18]
========================================================
-> Details for rule "sunrise to sunset (start)" ({c3697476-8b88-4822-b7de-9754431b3efc}):

Rule is enabled
Rule is inactive
Rule is executable

Events:

    0. ->                    Europe/Vienna (Today) -> event: "sunrise changed"

States:

Actions:

    0. ->                                Countdown -> action: "restart"
--------------------------------------------------------

So I don't know which countdown is meant. Please insert device name.

**Comment by t-mon** [comment]
thanks, good point!

fiy...the event `"sunrise changed"` will always trigger at midnight, when the date for the new sunrise value will change. if you want to do something at sunrise, please use the `sunrise` event.
